
live_config_reload = true
import = [
    "~/.config/alacritty/alacritty.defaults.toml",
    "~/.config/alacritty/alacritty.os.toml",
    "~/.config/alacritty/alacritty.host.toml",
    "~/.config/alacritty/colors/kolmila.toml",
]

[env]
TERM = "xterm-256color"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
decorations = "full"

[window.padding]
x = 2
y = 2

[keyboard]
bindings = [{ key = "Insert", mods = "Shift", action = "Paste" }]
